-- ============================================================
-- ERP Schema: Trip Master Folder + DB Sanitization
-- Run in Supabase SQL Editor
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. CREATE trips TABLE (Master Trip Folder)
-- ────────────────────────────────────────────────────────────

CREATE TABLE trips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Semantic ID: EZ-YYMM001pkg (generated by app layer)
  trip_id text NOT NULL,

  status text NOT NULL DEFAULT 'ENQUIRY'
    CHECK (status IN ('ENQUIRY', 'PROPOSING', 'ACTIVE_BOOKING', 'COMPLETED')),

  client_id uuid REFERENCES clients(id) ON DELETE SET NULL,
  created_by uuid REFERENCES users(id) ON DELETE SET NULL,

  destination text,
  travel_start date,
  travel_end date,
  pax_adults integer DEFAULT 1,
  pax_children integer DEFAULT 0,

  -- Proposal linkage (array of proposal UUIDs)
  proposal_ids uuid[] DEFAULT '{}',
  winning_proposal_id uuid REFERENCES proposals(id) ON DELETE SET NULL,

  -- Booking linkage
  booking_id uuid, -- will FK to bookings once booking is created

  -- Handover compliance checklist
  passports_verified boolean DEFAULT false,
  pan_verified boolean DEFAULT false,
  initial_deposit_received boolean DEFAULT false,

  notes text,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  -- Integrity: semantic ID must be globally unique
  CONSTRAINT uq_trips_trip_id UNIQUE (trip_id)
);

-- Indexes
CREATE INDEX idx_trips_status ON trips(status);
CREATE INDEX idx_trips_client ON trips(client_id);
CREATE INDEX idx_trips_travel_start ON trips(travel_start);
CREATE INDEX idx_trips_trip_id ON trips(trip_id);

-- Auto-update updated_at
CREATE TRIGGER set_trips_updated_at
  BEFORE UPDATE ON trips
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ────────────────────────────────────────────────────────────
-- 2. ADD trip_id COLUMN TO bookings TABLE
--    Links each booking back to its master trip folder
-- ────────────────────────────────────────────────────────────

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS trip_id text;

CREATE INDEX IF NOT EXISTS idx_bookings_trip_id ON bookings(trip_id);


-- ────────────────────────────────────────────────────────────
-- 3. TRIP SEQUENCE FUNCTION
--    Server-side atomic sequence for semantic IDs
-- ────────────────────────────────────────────────────────────

-- Sequence tracking table
CREATE TABLE IF NOT EXISTS trip_sequences (
  period_key text PRIMARY KEY, -- e.g. '2606'
  last_seq integer NOT NULL DEFAULT 0
);

-- Atomic next-sequence RPC
CREATE OR REPLACE FUNCTION next_trip_sequence(period_key text)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  next_val integer;
BEGIN
  INSERT INTO trip_sequences (period_key, last_seq)
  VALUES (period_key, 1)
  ON CONFLICT (period_key) DO UPDATE
    SET last_seq = trip_sequences.last_seq + 1
  RETURNING last_seq INTO next_val;

  RETURN next_val;
END;
$$;


-- ────────────────────────────────────────────────────────────
-- 4. DATABASE SANITIZATION
--    Remove stale columns & triggers from booking_payments
-- ────────────────────────────────────────────────────────────

-- 4a. Drop legacy trigger that references booking_payments
--     (refresh_booking_next_payment updates denorm fields on bookings)
DROP TRIGGER IF EXISTS update_booking_payment_summary ON booking_payments;

-- 4b. Drop the legacy trigger function
DROP FUNCTION IF EXISTS refresh_booking_next_payment CASCADE;

-- 4c. Drop legacy indexes that reference columns we're removing
DROP INDEX IF EXISTS idx_booking_payments_direction;
DROP INDEX IF EXISTS idx_booking_payments_supplier;

-- 4d. Drop legacy columns from booking_payments
--     These were added in 20260423_ops_bookings.sql but the table was
--     recreated in 20260425_bookings_rebuild.sql without them.
--     If they exist (from a partial migration state), remove them.
ALTER TABLE booking_payments DROP COLUMN IF EXISTS direction;
ALTER TABLE booking_payments DROP COLUMN IF EXISTS supplier_id;
ALTER TABLE booking_payments DROP COLUMN IF EXISTS client_id;
ALTER TABLE booking_payments DROP COLUMN IF EXISTS component_type;
ALTER TABLE booking_payments DROP COLUMN IF EXISTS component_id;


-- ────────────────────────────────────────────────────────────
-- 5. RECREATE PAYMENT SUMMARY TRIGGER (clean version)
--    Uses only columns that exist in the rebuilt booking_payments
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION refresh_booking_next_payment()
RETURNS TRIGGER AS $$
DECLARE
  target_booking_id uuid;
BEGIN
  target_booking_id := COALESCE(NEW.booking_id, OLD.booking_id);
  UPDATE bookings
  SET
    total_paid = COALESCE((
      SELECT SUM(amount) FROM booking_payments
      WHERE booking_id = target_booking_id AND status = 'paid'
    ), 0),
    next_payment_date = (
      SELECT MIN(due_date) FROM booking_payments
      WHERE booking_id = target_booking_id AND status = 'pending' AND due_date IS NOT NULL
    ),
    next_payment_amount = (
      SELECT amount FROM booking_payments
      WHERE booking_id = target_booking_id AND status = 'pending' AND due_date IS NOT NULL
      ORDER BY due_date ASC LIMIT 1
    )
  WHERE id = target_booking_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_booking_payment_summary
  AFTER INSERT OR UPDATE OR DELETE ON booking_payments
  FOR EACH ROW EXECUTE FUNCTION refresh_booking_next_payment();


-- ────────────────────────────────────────────────────────────
-- 6. RLS POLICIES FOR trips TABLE
-- ────────────────────────────────────────────────────────────

ALTER TABLE trips ENABLE ROW LEVEL SECURITY;

-- Agents see only their own trips
CREATE POLICY trips_agent_select ON trips
  FOR SELECT USING (
    created_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role IN ('super_admin', 'manager')
    )
  );

CREATE POLICY trips_agent_insert ON trips
  FOR INSERT WITH CHECK (created_by = auth.uid());

CREATE POLICY trips_agent_update ON trips
  FOR UPDATE USING (
    created_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role IN ('super_admin', 'manager')
    )
  );

-- Service role bypasses RLS (used by createServiceClient)
