-- Baseline Schema Initialization

CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['agent'::text, 'manager'::text, 'accounts'::text, 'operations'::text, 'super_admin'::text])),
  agency_name text,
  logo_url text,
  whatsapp_number text,
  default_currency text DEFAULT 'INR'::text,
  default_payment_terms jsonb,
  margin_threshold_pct numeric DEFAULT 12,
  rounding_unit integer DEFAULT 0,
  tc_content text,
  tc_version integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid,
  max_active_leads integer DEFAULT 10,
  manager_id uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.users(id)
);

CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_by uuid,
  full_name text NOT NULL,
  phone text NOT NULL UNIQUE,
  email text,
  nationality text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);

CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_by uuid,
  name text NOT NULL,
  type text CHECK (type = ANY (ARRAY['DMC'::text, 'hotel'::text, 'airline'::text, 'car'::text, 'activity'::text, 'other'::text])),
  country text,
  contact_name text,
  contact_email text,
  contact_phone text,
  payment_terms_days integer,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  category text,
  payment_terms text,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT suppliers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);

CREATE TABLE public.supplier_surcharges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid,
  label text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  surcharge_type text CHECK (surcharge_type = ANY (ARRAY['per_night'::text, 'flat'::text, 'percent'::text])),
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplier_surcharges_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_surcharges_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);

CREATE TABLE public.website_enquiries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  email text,
  phone text,
  destination text,
  travel_date date,
  date_flexible boolean DEFAULT false,
  flexibility_days integer,
  adults integer,
  children integer DEFAULT 0,
  children_ages text,
  budget_range text,
  budget_type text,
  number_of_nights integer,
  hotel_category text,
  special_requirements text,
  whatsapp_opted boolean DEFAULT false,
  source text,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'qualified'::text, 'proposal_sent'::text, 'won'::text, 'lost'::text, 'spam'::text, 'closed'::text])),
  notes text,
  client_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_to uuid,
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  lead_temperature text DEFAULT 'warm'::text CHECK (lead_temperature = ANY (ARRAY['hot'::text, 'warm'::text, 'cold'::text, 'lost'::text])),
  follow_up_date date,
  last_contacted_at timestamp with time zone,
  converted_at timestamp with time zone,
  lost_reason text,
  lost_notes text,
  requirement_type text DEFAULT 'package'::text CHECK (requirement_type = ANY (ARRAY['package'::text, 'flight'::text, 'hotel'::text, 'transfer'::text, 'visa'::text])),
  requirement_details jsonb DEFAULT '{}'::jsonb,
  assigned_to_ops uuid,
  temperature text DEFAULT 'warm',
  pipeline_stage text DEFAULT 'in_progress',
  service_requirements jsonb DEFAULT '[]'::jsonb,
  customer_name text,
  trip_id text,
  CONSTRAINT website_enquiries_pkey PRIMARY KEY (id),
  CONSTRAINT website_enquiries_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT website_enquiries_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT website_enquiries_assigned_to_ops_fkey FOREIGN KEY (assigned_to_ops) REFERENCES public.users(id)
);

CREATE TABLE public.proposals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_by uuid,
  client_id uuid,
  parent_proposal_id uuid,
  version integer DEFAULT 1,
  status text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'viewed'::text, 'confirmed'::text, 'cancelled'::text])),
  pricing_mode text DEFAULT 'standard'::text CHECK (pricing_mode = ANY (ARRAY['standard'::text, 'tiered'::text])),
  title text,
  destination text,
  travel_start date,
  travel_end date,
  pax_adults integer DEFAULT 1,
  pax_children integer DEFAULT 0,
  children_ages integer[],
  currency text DEFAULT 'INR'::text,
  special_notes text,
  dietary_notes text,
  gst_enabled boolean DEFAULT false,
  gst_rate numeric DEFAULT 5,
  tcs_enabled boolean DEFAULT false,
  rounding_unit integer,
  discount_amount numeric DEFAULT 0,
  discount_note text,
  cover_image_url text,
  cover_image_source text CHECK (cover_image_source = ANY (ARRAY['curated'::text, 'ai_suggested'::text, 'approved'::text])),
  cover_image_approved_at timestamp with time zone,
  cover_image_approved_by uuid,
  share_token text UNIQUE,
  published_data jsonb,
  draft_data jsonb,
  draft_differs_from_published boolean DEFAULT false,
  payment_terms jsonb,
  tc_version integer,
  visa_check_source text DEFAULT 'static'::text,
  visa_section_enabled boolean DEFAULT false,
  flight_expires_at timestamp with time zone,
  land_expires_at timestamp with time zone,
  last_viewed_at timestamp with time zone,
  view_count integer DEFAULT 0,
  confirmed_at timestamp with time zone,
  confirmed_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  quote_type text DEFAULT 'itemised'::text CHECK (quote_type = ANY (ARRAY['package'::text, 'itemised'::text])),
  package_cp_per_person numeric,
  package_sp_per_person numeric,
  trip_cities jsonb,
  land_cp numeric,
  land_sp numeric,
  pricing_display_mode text DEFAULT 'per_person'::text CHECK (pricing_display_mode = ANY (ARRAY['per_person'::text, 'total'::text, 'both'::text])),
  total_sp numeric,
  tcs_rate numeric DEFAULT 5,
  enquiry_id uuid,
  passenger_details jsonb,
  num_rooms integer DEFAULT 1,
  extra_beds integer DEFAULT 0,
  num_nights integer,
  cities_visited text[],
  route_signature text,
  trip_id text,
  CONSTRAINT proposals_pkey PRIMARY KEY (id),
  CONSTRAINT proposals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT proposals_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT proposals_parent_proposal_id_fkey FOREIGN KEY (parent_proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT proposals_cover_image_approved_by_fkey FOREIGN KEY (cover_image_approved_by) REFERENCES public.users(id),
  CONSTRAINT proposals_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES public.website_enquiries(id)
);

CREATE TABLE public.proposal_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  published_at timestamp with time zone DEFAULT now(),
  published_by uuid,
  CONSTRAINT proposal_versions_pkey PRIMARY KEY (id),
  CONSTRAINT proposal_versions_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT proposal_versions_published_by_fkey FOREIGN KEY (published_by) REFERENCES public.users(id)
);

CREATE TABLE public.proposal_tiers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  label text NOT NULL,
  pax_count integer NOT NULL,
  sort_order integer DEFAULT 0,
  CONSTRAINT proposal_tiers_pkey PRIMARY KEY (id),
  CONSTRAINT proposal_tiers_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id)
);

CREATE TABLE public.hotels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  tier_id uuid,
  supplier_id uuid,
  name text NOT NULL,
  city text NOT NULL,
  check_in date NOT NULL,
  check_out date NOT NULL,
  nights integer,
  room_type text,
  meal_plan text CHECK (meal_plan = ANY (ARRAY['RO'::text, 'BB'::text, 'HB'::text, 'FB'::text, 'AI'::text])),
  star_rating integer,
  room_view text,
  is_non_refundable boolean DEFAULT false,
  hotel_cancellation_slabs jsonb,
  cp_per_night numeric,
  sp_per_night numeric,
  cwb_cp numeric,
  cwb_sp numeric,
  cnb_cp numeric,
  cnb_sp numeric,
  description text,
  description_approved boolean DEFAULT false,
  early_checkin_requested boolean DEFAULT false,
  late_checkout_requested boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hotels_pkey PRIMARY KEY (id),
  CONSTRAINT hotels_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT hotels_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.proposal_tiers(id),
  CONSTRAINT hotels_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);

CREATE TABLE public.flights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  tier_id uuid,
  supplier_id uuid,
  flight_number text NOT NULL,
  airline text,
  origin_iata text,
  origin_city text,
  destination_iata text,
  destination_city text,
  departure_at timestamp with time zone,
  arrival_at timestamp with time zone,
  aircraft_type text,
  cabin_class text,
  baggage_allowance text,
  is_non_refundable boolean DEFAULT false,
  cp_total numeric,
  sp_total numeric,
  fare_expires_at timestamp with time zone,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  refundable_status text DEFAULT 'non_refundable'::text CHECK (refundable_status = ANY (ARRAY['refundable'::text, 'non_refundable'::text, 'partially_refundable'::text])),
  cancellation_policy_text text,
  layovers jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT flights_pkey PRIMARY KEY (id),
  CONSTRAINT flights_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT flights_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.proposal_tiers(id),
  CONSTRAINT flights_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);

CREATE TABLE public.itinerary_days (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  day_number integer NOT NULL,
  date date NOT NULL,
  city text,
  heading text,
  description text,
  overnight_city text,
  created_at timestamp with time zone DEFAULT now(),
  day_type text CHECK (day_type = ANY (ARRAY['arrival'::text, 'tour'::text, 'transfer'::text, 'departure'::text, 'flight'::text])),
  raw_description text,
  CONSTRAINT itinerary_days_pkey PRIMARY KEY (id),
  CONSTRAINT itinerary_days_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id)
);

CREATE TABLE public.itinerary_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  itinerary_day_id uuid,
  proposal_id uuid,
  tier_id uuid,
  supplier_id uuid,
  type text CHECK (type = ANY (ARRAY['transfer'::text, 'sightseeing'::text, 'meal'::text, 'activity'::text, 'free_time'::text, 'other'::text])),
  option_mode text CHECK (option_mode = ANY (ARRAY['pvt_only'::text, 'sic_only'::text, 'tbd'::text, 'dual'::text])),
  client_choice text CHECK (client_choice = ANY (ARRAY['pvt'::text, 'sic'::text])),
  confirmed_cp numeric,
  confirmed_sp numeric,
  confirmed_basis text CHECK (confirmed_basis = ANY (ARRAY['per_vehicle'::text, 'per_person'::text])),
  pvt_cp numeric,
  pvt_sp numeric,
  pvt_basis text CHECK (pvt_basis = ANY (ARRAY['per_vehicle'::text, 'per_person'::text])),
  pvt_vehicle_type text,
  sic_cp numeric,
  sic_sp numeric,
  sic_basis text CHECK (sic_basis = ANY (ARRAY['per_vehicle'::text, 'per_person'::text])),
  start_time time without time zone,
  end_time time without time zone,
  location text,
  details jsonb,
  is_optional boolean DEFAULT false,
  show_in_pdf boolean DEFAULT true,
  conflict_flagged boolean DEFAULT false,
  conflict_acknowledged boolean DEFAULT false,
  conflict_note text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT itinerary_activities_pkey PRIMARY KEY (id),
  CONSTRAINT itinerary_activities_itinerary_day_id_fkey FOREIGN KEY (itinerary_day_id) REFERENCES public.itinerary_days(id),
  CONSTRAINT itinerary_activities_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT itinerary_activities_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.proposal_tiers(id),
  CONSTRAINT itinerary_activities_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);

CREATE TABLE public.line_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  tier_id uuid,
  supplier_id uuid,
  type text CHECK (type = ANY (ARRAY['transfer'::text, 'activity'::text, 'visa'::text, 'surcharge'::text, 'other'::text, 'ancillary'::text])),
  description text NOT NULL,
  date date,
  cp numeric DEFAULT 0,
  sp numeric DEFAULT 0,
  pricing_basis text CHECK (pricing_basis = ANY (ARRAY['per_vehicle'::text, 'per_person'::text, 'flat'::text])),
  is_optional boolean DEFAULT false,
  is_included boolean DEFAULT true,
  show_in_pdf boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  per_person boolean DEFAULT false,
  include_in_total boolean DEFAULT true,
  is_addon boolean DEFAULT false,
  CONSTRAINT line_items_pkey PRIMARY KEY (id),
  CONSTRAINT line_items_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT line_items_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.proposal_tiers(id),
  CONSTRAINT line_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);

CREATE TABLE public.proposal_content_blocks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  type text CHECK (type = ANY (ARRAY['packing_list'::text, 'weather'::text, 'why_book_us'::text, 'destination_highlights'::text, 'insurance_upsell'::text, 'lounge_upsell'::text, 'custom'::text])),
  content jsonb NOT NULL,
  is_included boolean DEFAULT false,
  created_by text CHECK (created_by = ANY (ARRAY['ai'::text, 'agent'::text])),
  sort_order integer DEFAULT 0,
  CONSTRAINT proposal_content_blocks_pkey PRIMARY KEY (id),
  CONSTRAINT proposal_content_blocks_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id)
);

CREATE TABLE public.visa_compliance_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  destination_country text NOT NULL,
  nationality text NOT NULL,
  visa_required boolean DEFAULT false,
  visa_type text,
  passport_validity_months integer,
  transit_visa_note text,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visa_compliance_rules_pkey PRIMARY KEY (id)
);

CREATE TABLE public.travel_time_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  city_a text NOT NULL,
  city_b text NOT NULL,
  country text,
  estimated_minutes integer NOT NULL,
  cached_at timestamp with time zone DEFAULT now(),
  CONSTRAINT travel_time_cache_pkey PRIMARY KEY (id)
);

CREATE TABLE public.client_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid,
  proposal_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['credit'::text, 'debit'::text])),
  amount numeric NOT NULL,
  description text NOT NULL,
  reference text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT client_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT client_ledger_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT client_ledger_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT client_ledger_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);

CREATE TABLE public.forex_locks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  from_currency text NOT NULL,
  to_currency text DEFAULT 'INR'::text,
  locked_rate numeric NOT NULL,
  locked_at timestamp with time zone DEFAULT now(),
  last_checked_at timestamp with time zone,
  current_rate numeric,
  drift_pct numeric,
  alert_fired boolean DEFAULT false,
  CONSTRAINT forex_locks_pkey PRIMARY KEY (id),
  CONSTRAINT forex_locks_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id)
);

CREATE TABLE public.raw_quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  supplier_id uuid,
  source_type text CHECK (source_type = ANY (ARRAY['pdf'::text, 'excel'::text, 'text'::text])),
  file_url text,
  raw_text text,
  parsed_json jsonb,
  sanitisation_flags jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT raw_quotes_pkey PRIMARY KEY (id),
  CONSTRAINT raw_quotes_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT raw_quotes_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);

CREATE TABLE public.proposal_acceptance_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  version integer NOT NULL,
  event_type text CHECK (event_type = ANY (ARRAY['viewed'::text, 'tc_accepted'::text, 'visa_acknowledged'::text, 'confirmed'::text, 'addon_selected'::text, 'tier_selected'::text])),
  ip_address text,
  user_agent text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT proposal_acceptance_log_pkey PRIMARY KEY (id),
  CONSTRAINT proposal_acceptance_log_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id)
);

CREATE TABLE public.proposal_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  user_id uuid,
  message text NOT NULL,
  mentions text[],
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT proposal_comments_pkey PRIMARY KEY (id),
  CONSTRAINT proposal_comments_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT proposal_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.website_destinations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  tagline text,
  description text,
  country text,
  region text,
  tags text[],
  cover_image text,
  gallery text[],
  duration_days integer,
  price_from numeric,
  currency text NOT NULL DEFAULT 'INR'::text,
  is_pilgrimage boolean DEFAULT false,
  published boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT website_destinations_pkey PRIMARY KEY (id)
);

CREATE TABLE public.website_blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  excerpt text,
  content text,
  hero_image text,
  tags text[],
  author text NOT NULL DEFAULT 'EzTrips Team'::text,
  published boolean DEFAULT false,
  published_at timestamp with time zone,
  seo_title text,
  seo_description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT website_blog_posts_pkey PRIMARY KEY (id)
);

CREATE TABLE public.website_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  subtitle text,
  destination text,
  duration_days integer,
  price_from numeric,
  currency text NOT NULL DEFAULT 'INR'::text,
  cover_image text,
  highlights text[],
  itinerary_days jsonb,
  inclusions text[],
  exclusions text[],
  published boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  price_3star numeric,
  price_4star numeric,
  price_5star numeric,
  destination_slug text,
  nights integer,
  sample_hotels jsonb,
  terms text,
  price_valid_from date,
  price_valid_to date,
  gallery text[],
  CONSTRAINT website_packages_pkey PRIMARY KEY (id),
  CONSTRAINT website_packages_destination_slug_fkey FOREIGN KEY (destination_slug) REFERENCES public.website_destinations(slug)
);

CREATE TABLE public.enquiry_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enquiry_id uuid NOT NULL,
  user_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['call_outgoing'::text, 'call_incoming'::text, 'call_missed'::text, 'whatsapp'::text, 'email'::text, 'sms'::text, 'meeting'::text, 'site_visit'::text, 'note'::text, 'follow_up'::text, 'status_change'::text])),
  subject text,
  body text,
  duration_minutes integer,
  outcome text,
  follow_up_date date,
  follow_up_done boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT enquiry_activities_pkey PRIMARY KEY (id),
  CONSTRAINT enquiry_activities_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES public.website_enquiries(id),
  CONSTRAINT enquiry_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  client_id uuid,
  supplier_id uuid,
  created_by uuid,
  booking_type text NOT NULL CHECK (booking_type = ANY (ARRAY['package'::text, 'hotel'::text, 'land'::text, 'flight'::text])),
  title text NOT NULL,
  reference_number text,
  destination text,
  travel_start date,
  travel_end date,
  pax_adults integer DEFAULT 1,
  pax_children integer DEFAULT 0,
  currency text DEFAULT 'INR'::text,
  cost_price numeric DEFAULT 0,
  sell_price numeric DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'blocked'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  blocking_reference text,
  blocking_expires_at timestamp with time zone,
  total_paid numeric DEFAULT 0,
  next_payment_date date,
  next_payment_amount numeric,
  internal_notes text,
  assigned_to uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  passenger_details_completed boolean DEFAULT false,
  passenger_details_completed_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  trip_id text,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id),
  CONSTRAINT bookings_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT bookings_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT bookings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT bookings_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id)
);

CREATE TABLE public.booking_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL,
  details jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_logs_pkey PRIMARY KEY (id),
  CONSTRAINT booking_logs_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.booking_emails (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  supplier_id uuid,
  to_email text,
  cc_email text,
  subject text NOT NULL,
  body text NOT NULL,
  template_type text,
  direction text DEFAULT 'outbound'::text CHECK (direction = ANY (ARRAY['outbound'::text, 'inbound'::text])),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'failed'::text])),
  sent_at timestamp with time zone,
  sent_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_emails_pkey PRIMARY KEY (id),
  CONSTRAINT booking_emails_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_emails_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT booking_emails_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.users(id)
);

CREATE TABLE public.vouchers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  supplier_type text NOT NULL CHECK (supplier_type = ANY (ARRAY['hotel'::text, 'flight'::text, 'activity'::text, 'transfer'::text])),
  supplier_name text,
  booking_reference text,
  content jsonb NOT NULL,
  pdf_url text,
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  email_sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vouchers_pkey PRIMARY KEY (id),
  CONSTRAINT vouchers_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);

CREATE TABLE public.booking_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  item_type text NOT NULL CHECK (item_type = ANY (ARRAY['flight_segment'::text, 'hotel_room'::text, 'transfer'::text, 'activity'::text, 'meal_plan'::text, 'vehicle'::text])),
  label text NOT NULL,
  start_date date,
  end_date date,
  cost_price numeric,
  sell_price numeric,
  supplier_status text NOT NULL DEFAULT 'pending'::text CHECK (supplier_status = ANY (ARRAY['pending'::text, 'confirmation_requested'::text, 'on_hold'::text, 'confirmed'::text, 'modified'::text, 'cancelled'::text, 'completed'::text])),
  supplier_reference text,
  supplier_confirmed_at timestamp with time zone,
  supplier_notes text,
  details jsonb DEFAULT '{}'::jsonb,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  supplier_id uuid,
  availability_type text CHECK (availability_type = ANY (ARRAY['point_to_point'::text, 'at_disposal'::text])),
  daily_start_time time without time zone,
  daily_end_time time without time zone,
  driver_name text,
  driver_license text,
  driver_license_valid_until date,
  driver_insurance_type text CHECK (driver_insurance_type = ANY (ARRAY['basic'::text, 'premium'::text])),
  driver_notes text,
  itinerary jsonb DEFAULT '[]'::jsonb,
  include_payment_in_voucher boolean DEFAULT false,
  manager_approved boolean DEFAULT false,
  manager_approved_by uuid,
  manager_approved_at timestamp with time zone,
  approval_notes text,
  vendor_name text,
  vendor_email text,
  portal_name text,
  payment_due_date date,
  followup_count integer DEFAULT 0,
  last_followup_at timestamp with time zone,
  escalated boolean DEFAULT false,
  escalated_at timestamp with time zone,
  assigned_to uuid,
  cancellation_charge numeric,
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  refund_amount numeric,
  refund_status text CHECK (refund_status = ANY (ARRAY['pending'::text, 'approved'::text, 'processed'::text, 'rejected'::text])),
  property_contact_email text,
  portal_confirmation_id text,
  CONSTRAINT booking_items_pkey PRIMARY KEY (id),
  CONSTRAINT booking_items_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT booking_items_manager_approved_by_fkey FOREIGN KEY (manager_approved_by) REFERENCES public.users(id),
  CONSTRAINT booking_items_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id)
);

CREATE TABLE public.booking_passenger_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  pax_index integer NOT NULL,
  pax_count integer NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  gender text NOT NULL CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])),
  date_of_birth date,
  passport_urls text[],
  pan_urls text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_passenger_details_pkey PRIMARY KEY (id),
  CONSTRAINT booking_passenger_details_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);

CREATE TABLE public.website_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  content text DEFAULT ''::text,
  hero_image text,
  seo_title text,
  seo_description text,
  published boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT website_pages_pkey PRIMARY KEY (id)
);

CREATE TABLE public.website_homepage_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  section text NOT NULL,
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order integer DEFAULT 0,
  published boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT website_homepage_content_pkey PRIMARY KEY (id)
);

CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role text NOT NULL CHECK (role = ANY (ARRAY['agent'::text, 'manager'::text, 'accounts'::text, 'operations'::text, 'super_admin'::text])),
  permission text NOT NULL,
  description text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id)
);

CREATE TABLE public.payment_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  account_name text NOT NULL,
  account_number text,
  account_type text NOT NULL DEFAULT 'bank'::text CHECK (account_type = ANY (ARRAY['bank'::text, 'payment_gateway'::text, 'wallet'::text, 'upi'::text])),
  bank_name text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT payment_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.payment_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  is_template boolean NOT NULL DEFAULT true,
  payments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT payment_schedules_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.booking_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['full_dmc'::text, 'partial_dmc'::text, 'mixed'::text, 'individual'::text])),
  supplier_id uuid,
  booking_items_ids uuid[] DEFAULT '{}'::uuid[],
  total_cost numeric DEFAULT 0,
  payment_schedule_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'partial_paid'::text, 'paid'::text, 'cancelled'::text])),
  generated_payable_ids uuid[] DEFAULT '{}'::uuid[],
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_packages_pkey PRIMARY KEY (id),
  CONSTRAINT booking_packages_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_packages_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT booking_packages_payment_schedule_id_fkey FOREIGN KEY (payment_schedule_id) REFERENCES public.payment_schedules(id)
);

CREATE TABLE public.booking_package_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid NOT NULL,
  sequence integer NOT NULL,
  amount numeric NOT NULL,
  due_date date NOT NULL,
  reference_number text,
  paid_from_account_id uuid,
  received_in_account_id uuid,
  paid_from_account_snapshot text,
  received_in_account_snapshot text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'due'::text, 'partial_paid'::text, 'paid'::text, 'overdue'::text])),
  amount_paid numeric DEFAULT 0,
  paid_date date,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  include_in_voucher boolean DEFAULT false,
  approval_status text DEFAULT 'pending'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  payment_mode text CHECK (payment_mode = ANY (ARRAY['bank_transfer'::text, 'upi'::text, 'cash'::text, 'card'::text, 'cheque'::text, 'gateway'::text, 'portal_wallet'::text])),
  payment_proof_url text,
  version integer NOT NULL DEFAULT 1,
  CONSTRAINT booking_package_payments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_package_payments_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.booking_packages(id),
  CONSTRAINT booking_package_payments_paid_from_account_id_fkey FOREIGN KEY (paid_from_account_id) REFERENCES public.payment_accounts(id),
  CONSTRAINT booking_package_payments_received_in_account_id_fkey FOREIGN KEY (received_in_account_id) REFERENCES public.payment_accounts(id),
  CONSTRAINT booking_package_payments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);

CREATE TABLE public.booking_vouchers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  item_id uuid NOT NULL,
  voucher_number text NOT NULL UNIQUE,
  voucher_type text NOT NULL CHECK (voucher_type = ANY (ARRAY['hotel'::text, 'flight'::text, 'vehicle'::text, 'transfer'::text, 'activity'::text, 'dmc_package'::text, 'package'::text])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'generated'::text, 'sent'::text, 'downloaded'::text, 'used'::text, 'expired'::text])),
  triggered_by text CHECK (triggered_by = ANY (ARRAY['payment_received'::text, 'manager_approved'::text, 'driver_assigned'::text, 'manual'::text])),
  pdf_url text,
  pdf_generated_at timestamp with time zone,
  download_count integer DEFAULT 0,
  last_downloaded_at timestamp with time zone,
  sent_to_email text,
  sent_at timestamp with time zone,
  generation_notes text,
  data_snapshot jsonb,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_vouchers_pkey PRIMARY KEY (id),
  CONSTRAINT booking_vouchers_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_vouchers_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.booking_items(id),
  CONSTRAINT booking_vouchers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);

CREATE TABLE public.customer_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_type text DEFAULT 'payment'::text CHECK (payment_type = ANY (ARRAY['payment'::text, 'refund'::text, 'adjustment'::text])),
  payment_mode text CHECK (payment_mode = ANY (ARRAY['bank_transfer'::text, 'upi'::text, 'cash'::text, 'card'::text, 'cheque'::text, 'razorpay'::text, 'other'::text])),
  reference_number text,
  received_in_account_id uuid,
  received_date date NOT NULL DEFAULT CURRENT_DATE,
  notes text,
  recorded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_payments_pkey PRIMARY KEY (id),
  CONSTRAINT customer_payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT customer_payments_received_in_account_id_fkey FOREIGN KEY (received_in_account_id) REFERENCES public.payment_accounts(id),
  CONSTRAINT customer_payments_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id)
);

CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  invoice_number text NOT NULL UNIQUE,
  invoice_type text NOT NULL CHECK (invoice_type = ANY (ARRAY['proforma'::text, 'final'::text, 'credit_note'::text])),
  client_id uuid,
  line_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  subtotal numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  amount_paid numeric DEFAULT 0,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'paid'::text, 'partial_paid'::text, 'overdue'::text, 'cancelled'::text, 'void'::text])),
  due_date date,
  notes text,
  pdf_url text,
  sent_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT invoices_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);

CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  template_key text NOT NULL,
  subject_template text NOT NULL,
  body_template text NOT NULL,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);

CREATE TABLE public.enquiry_supplier_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enquiry_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  sent_by uuid,
  email_to text NOT NULL,
  email_subject text NOT NULL,
  email_body text NOT NULL,
  response_status text DEFAULT 'pending'::text CHECK (response_status = ANY (ARRAY['pending'::text, 'responded'::text, 'declined'::text, 'no_response'::text])),
  response_notes text,
  sent_at timestamp with time zone DEFAULT now(),
  responded_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT enquiry_supplier_requests_pkey PRIMARY KEY (id),
  CONSTRAINT enquiry_supplier_requests_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES public.website_enquiries(id),
  CONSTRAINT enquiry_supplier_requests_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT enquiry_supplier_requests_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.users(id)
);

CREATE TABLE public.lookup_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  value text NOT NULL,
  label text NOT NULL,
  group_name text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lookup_items_pkey PRIMARY KEY (id)
);

CREATE TABLE public.trips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trip_id text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'ENQUIRY'::text CHECK (status = ANY (ARRAY['ENQUIRY'::text, 'PROPOSING'::text, 'ACTIVE_BOOKING'::text, 'COMPLETED'::text])),
  client_id uuid,
  created_by uuid,
  destination text,
  travel_start date,
  travel_end date,
  pax_adults integer DEFAULT 1,
  pax_children integer DEFAULT 0,
  proposal_ids uuid[] DEFAULT '{}'::uuid[],
  winning_proposal_id uuid,
  booking_id uuid,
  passports_verified boolean DEFAULT false,
  pan_verified boolean DEFAULT false,
  initial_deposit_received boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT trips_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT trips_winning_proposal_id_fkey FOREIGN KEY (winning_proposal_id) REFERENCES public.proposals(id)
);

CREATE TABLE public.trip_sequences (
  period_key text NOT NULL,
  last_seq integer NOT NULL DEFAULT 0,
  CONSTRAINT trip_sequences_pkey PRIMARY KEY (period_key)
);
